services:
  database:
    image: 'postgres'
    container_name: bookstore_db
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=5433

  fastapi:
    depends_on:
      - database
    image: bookstore_backend_image
    pull_policy: never
    container_name: bookstore_backend
    build: 
      context: ./fastapi
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8000:8000

  nextjs:
    image: bookstore_frontend_image
    pull_policy: never
    container_name: bookstore_frontend
    build: 
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - 3000:3000