"""Updated status enum.

Revision ID: 89681c809718
Revises: 36d6fc8fcad4
Create Date: 2025-01-26 05:17:04.629979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '89681c809718'
down_revision: Union[str, None] = '36d6fc8fcad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='book_status',
        new_values=['PUBLISHED', 'DRAFT', 'NA'],
        affected_columns=[TableReference(table_schema='public', table_name='books', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='book_status',
        new_values=['PUBLISHED', 'DRAFT'],
        affected_columns=[TableReference(table_schema='public', table_name='books', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
